# Generated by Django 6.0.5 on 2026-06-01 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SequencingRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('illumina_novaseq', 'Illumina NovaSeq'), ('illumina_nextseq', 'Illumina NextSeq'), ('illumina_miseq', 'Illumina MiSeq'), ('mock', 'Mock (Test Data)')], default='mock', max_length=32)),
                ('sequencing_type', models.CharField(choices=[('WES', 'Whole Exome Sequencing'), ('WGS', 'Whole Genome Sequencing')], default='WES', max_length=8)),
                ('read_length', models.IntegerField(default=150)),
                ('reference_genome', models.CharField(choices=[('GRCh38', 'GRCh38 / hg38'), ('GRCh37', 'GRCh37 / hg19'), ('mock_btk', 'Mock BTK (Test)')], default='mock_btk', max_length=16)),
                ('fastq_r1', models.FileField(upload_to='fastq/')),
                ('fastq_r2', models.FileField(blank=True, null=True, upload_to='fastq/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('qc', 'Quality Control'), ('aligning', 'Aligning Reads'), ('sorting', 'Sorting BAM'), ('calling_variants', 'Calling Variants'), ('parsing_vcf', 'Parsing VCF'), ('annotating', 'Annotating Variants'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=32)),
                ('progress_percent', models.IntegerField(default=0)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('error_message', models.TextField(blank=True)),
                ('qc_metrics', models.JSONField(default=dict)),
                ('bam_path', models.CharField(blank=True, max_length=512)),
                ('vcf_path', models.CharField(blank=True, max_length=512)),
                ('total_reads', models.BigIntegerField(blank=True, null=True)),
                ('aligned_reads', models.BigIntegerField(blank=True, null=True)),
                ('mean_coverage', models.FloatField(blank=True, null=True)),
                ('variants_found', models.IntegerField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequencing_runs', to='patients.sample')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
