# Generated by Django 6.0.5 on 2026-06-01 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sequencing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chromosome', models.CharField(db_index=True, max_length=16)),
                ('position', models.IntegerField()),
                ('variant_id', models.CharField(blank=True, max_length=32)),
                ('ref_allele', models.CharField(max_length=500)),
                ('alt_allele', models.CharField(max_length=500)),
                ('quality', models.FloatField(blank=True, null=True)),
                ('filter_status', models.CharField(default='.', max_length=64)),
                ('genotype', models.CharField(max_length=16)),
                ('read_depth', models.IntegerField(blank=True, null=True)),
                ('allele_frequency', models.FloatField(blank=True, null=True)),
                ('genotype_quality', models.IntegerField(blank=True, null=True)),
                ('raw_info', models.JSONField(default=dict)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='sequencing.sequencingrun')),
            ],
            options={
                'ordering': ['chromosome', 'position'],
            },
        ),
        migrations.CreateModel(
            name='VariantAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene_symbol', models.CharField(db_index=True, max_length=32)),
                ('transcript_id', models.CharField(blank=True, max_length=64)),
                ('consequence', models.CharField(max_length=64)),
                ('impact', models.CharField(choices=[('HIGH', 'High'), ('MODERATE', 'Moderate'), ('LOW', 'Low'), ('MODIFIER', 'Modifier')], db_index=True, max_length=16)),
                ('codon_change', models.CharField(blank=True, max_length=32)),
                ('amino_acid_change', models.CharField(blank=True, max_length=32)),
                ('protein_position', models.IntegerField(blank=True, null=True)),
                ('exon_number', models.CharField(blank=True, max_length=16)),
                ('is_iei_gene', models.BooleanField(db_index=True, default=False)),
                ('clinvar_significance', models.CharField(blank=True, max_length=64)),
                ('clinvar_id', models.CharField(blank=True, max_length=32)),
                ('sift_prediction', models.CharField(blank=True, max_length=32)),
                ('sift_score', models.FloatField(blank=True, null=True)),
                ('polyphen_prediction', models.CharField(blank=True, max_length=32)),
                ('polyphen_score', models.FloatField(blank=True, null=True)),
                ('extra_data', models.JSONField(default=dict)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='variants.variant')),
            ],
            options={
                'ordering': ['impact', 'gene_symbol'],
            },
        ),
        migrations.AddIndex(
            model_name='variant',
            index=models.Index(fields=['chromosome', 'position'], name='variants_va_chromos_5e0a7d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='variant',
            unique_together={('run', 'chromosome', 'position', 'ref_allele', 'alt_allele')},
        ),
    ]
