# Generated by Django 6.0.5 on 2026-06-01 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unknown')], max_length=1)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('clinical_info', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['external_id'],
            },
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tissue_type', models.CharField(choices=[('peripheral_blood', 'Peripheral Blood'), ('bone_marrow', 'Bone Marrow'), ('saliva', 'Saliva'), ('skin_biopsy', 'Skin Biopsy'), ('other', 'Other')], max_length=32)),
                ('collection_date', models.DateField()),
                ('sample_barcode', models.CharField(blank=True, max_length=64)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='patients.patient')),
            ],
            options={
                'ordering': ['-collection_date'],
            },
        ),
    ]
